# -*- coding: utf-8 -*-
"""Hierarchical_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BG4-dRdzlLtXITSJwpsZU7x3sfO3ksR5
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from scipy.spatial.distance import cdist

df = pd.read_csv('/content/breast-cancer.csv')

df

df.info()

df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 2})

X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

hc = AgglomerativeClustering(n_clusters=2, metric='euclidean', linkage='ward')
cluster_labels = hc.fit_predict(X_scaled)

def align_labels(y_true, y_cluster):
    mapped_labels = np.zeros_like(y_cluster)
    for i in range(2):
        mask = (y_cluster == i)
        if np.sum(mask) > 0:
            majority_label = np.bincount(y_true[mask]).argmax()
            mapped_labels[mask] = majority_label
    return mapped_labels

y_pred = align_labels(y_encoded, cluster_labels)

accuracy = accuracy_score(y_encoded, y_pred)
conf_matrix = confusion_matrix(y_encoded, y_pred)
class_report = classification_report(y_encoded, y_pred, target_names=['M', 'B'])

print(f"Accuracy Score: {accuracy * 100:.2f}%\n")
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

def predict_new_samples(new_data, X_trained, cluster_assignments, scaler_trained, label_encoder, cluster_mapping):
    new_data_scaled = scaler_trained.transform(new_data)

    centroid_0 = X_trained[cluster_assignments == 0].mean(axis=0)
    centroid_1 = X_trained[cluster_assignments == 1].mean(axis=0)
    centroids = np.vstack([centroid_0, centroid_1])

    distances = cdist(new_data_scaled, centroids, metric='euclidean')
    predicted_clusters = np.argmin(distances, axis=1)

    mapped_predictions_numeric = np.array([cluster_mapping[c] for c in predicted_clusters])

    return label_encoder.inverse_transform(mapped_predictions_numeric)

cluster_to_true_map = {}
for i in range(2):

    mask_train = (cluster_labels == i)
    if np.sum(mask_train) > 0:

        majority_label = np.bincount(y_encoded[mask_train]).argmax()
        cluster_to_true_map[i] = majority_label

sample_data = X.iloc[[0]]
prediction = predict_new_samples(sample_data, X_scaled, cluster_labels, scaler, le, cluster_to_true_map)
print(f"Prediction for the sample row: {prediction[0]}")